topics = ["A/B Testing", "A/B Testing Strategies", "AI Governance", "AI Tools", "ASP.NET", "Academic Publishing", 
    "Access to Medicines", "Accessibility", "Accounting Principles", "Accreditation Bodies", "Action Research", "Activism", 
    "Actor-Network Theory", "Adaptability", "Adventure Tourism", "Adventure Travel", "Advertising", "Advertising Campaigns", 
    "Advertising Ethics", "Advocacy Groups", "Affect Studies", "Affiliate Marketing", "Affiliate Marketing Programs", 
    "Agile Methodologies", "Agile Project Management", "Algebra", "Algorithm Design", "Altmetrics", "Alumni Networking", 
    "Analytical Chemistry", "Analytics Tools", "Angel Investing", "Angel Investors", "Angular", "Animal Husbandry", 
    "Animal Rights", "Animal Rights Organizations", "Anthropological Archaeology", "Anthropology of Aging", 
    "Anthropology of Art", "Anthropology of Childhood", "Anthropology of Education", "Anthropology of Food", 
    "Anthropology of Gender", "Anthropology of Medicine", "Anthropology of Play", "Anthropology of Religion", 
    "Anthropology of Sport", "Anthropology of Technology", "Anthropology of Tourism", "Anthropology of Travel", 
    "Anthropology of Work", "Applied Mathematics", "Applied Research", "Apprenticeships", "Aquaponics", 
    "Archaeological Theory", "Architectural Conservation", "Architecture", "Archival Research", "Art Conservation", 
    "Art Criticism", "Art History", "Art Therapy", "Artifact Preservation", "Artificial Intelligence", "Arts Organizations", 
    "Arts and Culture", "Asset Allocation", "Athlete Development", "Auditing", "Augmented Reality", 
    "Augmented Reality Applications", "Author Studies", "Autonomous Systems", "Backpacking", "Baking", "Balance Sheet", 
    "Banking", "Basic Research", "Behavioral Economics", "Behavioral Finance", "Behavioral Health", 
    "Benefits of Online Learning", "Big Data", "Big Data Ethics", "Bilateral Relations", "Biochemistry", "Biodiversity", 
    "Bioenergy", "Bioethics", "Biology", "Biotechnology", "Blended Learning", "Blockchain", "Blockchain Platforms", 
    "Blockchain Technology", "Board Games", "Board of Directors", "Book Recommendations", "Botany", "Brain Development", 
    "Brain Disorders", "Brain Health", "Brain Imaging Techniques", "Brain-Computer Interfaces", "Brainstorming Techniques", 
    "Brand Management", "Brand Messaging", "Brewing Science", "Broadcasting", "Budgeting", "Building Relationships", 
    "Burnout Prevention", "Business Accelerators", "Business Analytics", "Business Book Clubs", "Business Competitions", 
    "Business Conferences", "Business Continuity Planning", "Business Development Programs", "Business Ethics", 
    "Business Ethics in Practice", "Business Forecasting", "Business Improvement Districts", "Business Incubators", 
    "Business Intelligence", "Business Intelligence Tools", "Business Model Canvas", "Business Networking Groups", 
    "Business Networks", "Business Partnerships", "Business Simulation Games", "Business Strategy", "C#", "C++", "CRM Tools", 
    "CSS", "Calculus", "Capacity Building", "Career Coaching", "Career Development", "Career Transition", 
    "Career Transition Coaching", "Case Competitions", "Case Studies", "Cash Flow Statement", "Cause Marketing", 
    "Cell Biology", "Certification Bodies", "Certification Programs", "Challenges in Online Learning", "Chamber of Commerce", 
    "Chambers of Commerce", "Change Management", "Character Design", "Charitable Organizations", "Chemical Engineering", 
    "Chemical Reactions", "Chemistry", "Chemistry in Daily Life", "Child Psychology", "Child Welfare", "Choreography", 
    "Chronic Diseases", "Cinematography", "Circular Economy", "Civic Education", "Civic Engagement",
    "Civic Engagement Organizations", "Civic Groups", "Civic Organizations", "Civic Participation", "Civic Responsibility", 
    "Civil Society Organizations", "Classic Literature", "Classical Archaeology", "Climate Change", "Climate Change Impact", 
    "Climate Policy", "Cloud Computing", "Cloud Services", "Clustering Algorithms", "Co-Working Spaces", "Coaching Techniques", 
    "Cocktail Culture", "Cognitive Behavioral Therapy", "Cognitive Functions", "Cognitive Science", "Collaborative Consumption", 
    "Collaborative Initiatives", "Collaborative Workspaces", "Collecting", "Collective Bargaining", 
    "Collective Impact Initiatives", "Commodities", "Communicable Diseases", "Communication Skills", 
    "Communication Skills Training", "Communication Theory", "Community Associations", "Community Colleges", 
    "Community Development", "Community Development Corporations", "Community Development Organizations", 
    "Community Engagement", "Community Ethics", "Community Foundations", "Community Health", "Community Outreach", 
    "Community Support Services", "Community-Based Health Programs", "Community-Based Research", "Comparative Politics", 
    "Comparative Studies", "Competitive Analysis", "Competitor Analysis", "Compliance Training", "Computer Ethics",
    "Computer Graphics", "Computer Vision", "Computer Vision Tools", "Conferences and Summits", "Confidentiality", 
    "Conflict Resolution", "Conflict Resolution Programs", "Conflict Resolution Training", "Consent", "Conservation Biology", 
    "Conservation Efforts", "Consulting", "Consumer Behavior", "Consumer Finance", "Consumer Psychology", 
    "Contemporary Literature", "Content Analysis", "Content Creation", "Content Marketing", "Content Marketing Strategy", 
    "Content Metrics", "Continuing Education", "Continuous Improvement", "Contract Work", "Conversion Rate Optimization", 
    "Cooking Techniques", "Core Values", "Corporate Accountability", "Corporate Communication", "Corporate Culture", 
    "Corporate Ethics", "Corporate Foundations", "Corporate Governance", "Corporate Identity", "Corporate Image", 
    "Corporate Philanthropy", "Corporate Reputation", "Corporate Social Responsibility", 
    "Corporate Social Responsibility Initiatives", "Corporate Social Responsibility Reporting", 
    "Corporate Social Responsibility Standards", "Cosmopolitanism", "Cost Accounting", "Counseling Techniques", 
    "Country Profiles", "Crafting", "Creative Problem Solving", "Creative Strategy", "Creative Writing", "Creativity", 
    "Creativity Workshops", "Credit Scores", "Criminal Justice", "Crisis Communication", "Crisis Counseling", 
    "Crisis Intervention", "Crisis Management", "Critical Theory", "Critical Thinking", "Cross-Border Work", 
    "Cross-Cultural Communication", "Cross-Cultural Management", "Cross-Cultural Studies", "Cross-Sector Partnerships", 
    "Crowdfunding", "Crowdfunding Platforms", "Crowdsourcing", "Crowdsourcing Platforms", "Cryptocurrency", 
    "Cryptocurrency Economics", "Cryptocurrency Exchanges", "Cryptocurrency Mining", "Cryptocurrency Trading", 
    "Cryptography", "Culinary Arts", "Culinary Entrepreneurship", "Culinary History", "Culinary Techniques", 
    "Culinary Travel", "Cultural Anthropology", "Cultural Appropriation", "Cultural Aspects of Nutrition", 
    "Cultural Competence", "Cultural Competence Training", "Cultural Criticism", "Cultural Cuisine", "Cultural Diplomacy", 
    "Cultural Exchange", "Cultural Festivals", "Cultural Geography", "Cultural Heritage", "Cultural Heritage Management", 
    "Cultural Heritage Preservation", "Cultural Heritage of Countries", "Cultural Identity", "Cultural Influences in Fashion", 
    "Cultural Intelligence", "Cultural Organizations", "Cultural Sensitivity", "Cultural Studies", "Cultural Studies Theory", 
    "Cultural Tourism", "Curation", "Customer Development", "Customer Feedback", "Customer Feedback Tools", 
    "Customer Journey Mapping", "Customer Relationship Management", "Customer Retention Strategies", "Customer Service", 
    "Customer Service Tools", "Customer Service Training", "Cyber Ethics", "Cyber Threats", "Cybersecurity", "Dance", 
    "Dance Therapy", "Data Analysis", "Data Analysis Techniques", "Data Analytics Platforms", "Data Collection Methods", 
    "Data Curation", "Data Governance", "Data Mining", "Data Privacy", "Data Protection", "Data Quality", "Data Science", 
    "Data Science Platforms", "Data Science Tools", "Data Sharing", "Data Structures", "Data Visualization", 
    "Data Visualization Tools", "Data Warehousing", "Data-Driven Marketing", "Database Management", "Debt Management", 
    "Decentralized Applications", "Decision Trees", "Deep Learning", "Demographics", "Derivatives", "Descriptive Analytics", 
    "Desert", "Design", "Design Sprints", "Design Thinking", "Design Thinking Workshops", "DevOps", "Development Economics", 
    "Developmental Psychology", "Diaspora Studies", "Dietary Guidelines", "Digital Art", "Digital Art Techniques", 
    "Digital Citizenship", "Digital Content Strategy", "Digital Forensics", "Digital Health", "Digital Humanities", 
    "Digital Literacy", "Digital Marketing", "Digital Media", "Digital Preservation", "Digital Therapeutics", 
    "Digital Transformation", "Digital Wallets", "Diplomacy", "Directing", "Disability Rights", "Disability Services", 
    "Disability Studies", "Disaster Management", "Disaster Recovery Planning", "Discourse Analysis", "Discrete Mathematics", 
    "Disease Prevention", "Display Advertising", "Distribution", "Diversity and Inclusion", "Diversity and Inclusion Training", 
    "Diversity in the Workplace", "Django", "Documentary Research", "Domestic Violence Prevention", "Drones", 
    "E-Learning Platforms", "E-commerce", "E-commerce Platforms", "E-learning", "ETL Processes", "Eco-Tourism", "Ecology", 
    "Econometrics", "Economic Conditions by Country", "Economic Development Organizations", "Economic Diplomacy", 
    "Economic Evaluation in Health", "Economic Geography", "Economic Growth", "Economic History", "Economic Indicators", 
    "Economic Policies", "Economic Theory", "Economics", "Ecosystem Management", "Ecosystem Services", "Edge Computing", 
    "Editing", "Educational Institutions", "Educational Psychology", "Educational Technology", "Elderly Care", 
    "Election Monitoring Organizations", "Electoral Reform", "Electoral Systems", "Electronic Health Records", 
    "Email Campaigns", "Email Marketing", "Email Marketing Metrics", "Email Marketing Tools", "Emergency Services", 
    "Emerging Economies", "Emerging Technologies", "Emotions and the Brain", "Employee Engagement", "Employee Rights", 
    "Employee Wellness Programs", "Employer Associations", "Employment Law", "Employment Services", "Energy Efficiency", 
    "Entomology", "Entrepreneurial Ecosystems", "Entrepreneurship", "Entrepreneurship Competitions", "Environmental Activism",
    "Environmental Anthropology", "Environmental Chemistry", "Environmental Economics", "Environmental Education", 
    "Environmental Ethics", "Environmental Organizations", "Environmental Policy", "Environmental Science", 
    "Environmental, Social, and Governance (ESG) Investing", "Epidemiology", "Epidemiology Research", "Estate Planning", 
    "Ethical Eating", "Ethical Hacking", "Ethical Investing", "Ethics", "Ethics Training", "Ethics in Business", 
    "Ethics in Research", "Ethics of Artificial Intelligence", "Ethics of Biotechnology", "Ethnic Studies", "Ethnoarchaeology", 
    "Ethnographic Research", "Ethnography", "Evaluation Research", "Evolutionary Biology", "Exchange-Traded Funds", 
    "Executive Compensation", "Exercise Science", "Exhibition Design", "Experiment Design", "Experimental Archaeology", 
    "Experimental Economics", "Express", "Extreme Sports", "Faith-Based Organizations", "Family Support Services", 
    "Fashion Design", "Fashion History", "Fashion Marketing", "Fashion Photography", "Fashion Trends", "Fashion and Identity", 
    "Feminism", "Feminist Theory", "Fiction vs. Non-Fiction", "Field Experiments", "Fieldwork", "Film Festivals",
    "Film Production", "Film Studies", "Financial Accounting", "Financial Analysis", "Financial Literacy", 
    "Financial Literacy Education", "Financial Management", "Financial Markets", "Financial Planning", "Financial Psychology", 
    "Financial Ratios", "Financial Regulations", "Financial Reporting", "Financial Statements", "Fine Arts", "Fiscal Policy", 
    "Fishing", "Fitness", "Fitness and Health", "Flask", "Focus Group Software", "Focus Groups", "Focus Techniques", 
    "Folklore", "Food History", "Food Photography", "Food Safety", "Food Science", "Food Security", "Food Security Programs", 
    "Food Sustainability", "Food Writing", "Food and Culture", "Foreign Aid", "Foreign Direct Investment", 
    "Forensic Accounting", "Forensic Science", "Forest", "Forex Trading", "Freelancer Platforms", "Freelancing", "Freshwater", 
    "Friendship Dynamics", "Future of Education", "Future of Renewable Energy", "Futurism", "Game Design", "Game Development", 
    "Game Theory", "Game Theory Applications", "Gardening", "Gastronomic Tourism", "Gastronomy", "Gender Equality", 
    "Gender Roles", "Gender Studies", "Gender and Politics", "Gender and Society", "Genealogy", "Genetic Engineering", 
    "Genetics", "Geographic Information Systems", "Geographical Features", "Geometry", "Geothermal Energy", "Gig Economy", 
    "Gig Economy Platforms", "Global Branding", "Global Citizenship", "Global Communication Strategies", 
    "Global Consumer Behavior", "Global Cuisines", "Global Energy Transition", "Global Ethics", "Global Gender Issues", 
    "Global Governance", "Global Health", "Global Health Equity", "Global Health Governance", "Global Health Initiatives", 
    "Global Health Partnerships", "Global Health Security", "Global Leadership", "Global Markets", "Global Mindset", 
    "Global Mobility", "Global Studies", "Global Supply Chains", "Global Talent Acquisition", "Global Talent Management", 
    "Global Team Dynamics", "Global Workforce Planning", "Globalization", "Globalization Trends", "Go", "Goal Setting", 
    "Government Accountability", "Government Structures", "Grant-Making Organizations", "Graphic Design", "Grassroots Activism", 
    "Grassroots Movements", "Green Business", "Growth Hacking", "HTML", "Hackathons", "Hardware Engineering", "Health Apps", 
    "Health Coaching", "Health Communication", "Health Disparities", "Health Economics", "Health Education", 
    "Health Informatics", "Health Information Exchange", "Health Information Technology", "Health Insurance", "Health Literacy", 
    "Health Policy Advocacy", "Health Policy Analysis", "Health Promotion", "Health Promotion Campaigns",
    "Health Systems Research", "Health Systems Resilience", "Health Systems Strengthening", "Health Technology Assessment", 
    "Health and Climate Change", "Health and Safety Regulations", "Healthcare Access", "Healthcare Collaborations", 
    "Healthcare Delivery Models", "Healthcare Financing", "Healthcare Innovation", "Healthcare Quality Improvement", 
    "Healthcare Reform", "Healthcare Systems", "Healthcare Workforce Development", "Healthy Eating", "Help Desk Software", 
    "Heritage Conservation", "Heritage Studies", "Hiking", "Historical Archaeology", "Historical Preservation", 
    "Historical Research", "History", "History of Nations", "Home Cooking", "Homelessness Services", "Homeowners Associations", 
    "Hospital Management", "Housing Stability Programs", "Human Resources", "Human Rights", "Human Rights Organizations", 
    "Human-Computer Interaction", "Humanitarian Intervention", "Humanitarian Organizations", "Hydroponics", "Hydropower", 
    "IT Support", "Image Processing", "Impact Investing", "Impact Investment Funds", "Impact Investors", "Impact Measurement", 
    "Incident Response", "Inclusion Strategies", "Income Statement", "Income Support Programs", "Incubators", 
    "Individual Sports", "Industrial Chemistry", "Industrial Design", "Industrial Organization", 
    "Industrial-Organizational Psychology", "Industry Analysis", "Industry Associations", "Industry Certification Programs", 
    "Industry Meetups", "Industry Trends", "Infectious Diseases", "Inflation", "Influencer Marketing", 
    "Influencer Partnerships", "Information Economics", "Information Literacy", "Information Security", 
    "Information Technology", "Innovation", "Innovation Hubs", "Innovation Labs", "Innovation Strategies", 
    "Innovation Workshops", "Inorganic Chemistry", "Installation Art", "Instructional Design", "Insurance", 
    "Integrated Care", "Integrated Health Services", "Intellectual Property", "Intellectual Property Ethics", 
    "Interdisciplinary Studies", "Interest Rates", "Interior Design", "Internal Communication", "Internal Controls", 
    "International Assignments", "International Business", "International Development", "International Development Policy", 
    "International Economics", "International HR Management", "International Law", "International Marketing", 
    "International Organizations", "International Recruitment", "International Relations", "International Relations Theory", 
    "International Trade", "International Trade Agreements", "Internships", "Interoperability in Healthcare", 
    "Interpersonal Skills", "Intersectionality", "Interview Preparation Workshops", "Interview Skills", "Interviews", 
    "Inventory Management", "Investment Analysis", "Investment Strategies", "Investor Pitch Days", "Investor Relations", 
    "IoT (Internet of Things)", "IoT Applications", "IoT Platforms", "Java", "JavaScript", "Job Search Strategies", 
    "Job Training Programs", "Journalism", "Journalism Ethics", "Kanban Method", "Keyword Research", "Knowledge Management", 
    "Kotlin", "LGBTQ+ Rights", "Labor Economics", "Labor Relations", "Landing Page Optimization", "Language Acquisition", 
    "Language Evolution", "Language Preservation", "Language and Identity", "Language and Power", "Languages Spoken", 
    "Law and Society", "Lead Generation", "Lead Generation Techniques", "Leadership", "Leadership Development", 
    "Leadership Retreats", "Leadership Skills Training", "Lean Management", "Lean Startup Principles", "Learning Communities", 
    "Learning Management Systems", "Legal Compliance", "Level Design", "Linguistic Anthropology", "Linguistic Diversity", 
    "Linguistics", "Link Building Strategies", "Literary Criticism", "Literary Genres", "Literature", "Literature and Society", 
    "Literature as a Reflection of Culture", "Live Chat Support", "Local Business Alliances", "Local History", "Local SEO", 
    "Logistics", "Longitudinal Studies", "Loyalty Programs", "MOOCs", "Machine Learning", "Machine Learning Algorithms", 
    "Machine Learning Libraries", "Machine Learning Platforms", "Machine Learning for Healthcare", "Macroeconomics", 
    "Malware Analysis", "Management Accounting", "Managerial Accounting", "Manufacturing Processes", "Marine Biology", 
    "Marine Ecosystems", "Market Analysis", "Market Psychology", "Market Research", "Market Research Tools", 
    "Market Structures", "Market Trends", "Market Validation", "Marketing Analytics", "Marketing Automation", 
    "Marketing Tools", "Marxist Theory", "Masculinity Studies", "Masterclasses", "Mastermind Groups", 
    "Maternal and Child Health", "Mathematical Proofs", "Mathematics", "Mathematics Education", "Mathematics in Technology", 
    "Mechatronics", "Media Ecology", "Media Ethics", "Media Literacy", "Media Relations", "Media Studies", 
    "Medicare and Medicaid", "Meditation", "Memory Studies", "Memory and Learning", "Mental Health", "Mental Health Awareness", 
    "Mental Health Awareness Programs", "Mental Health Disorders", "Mental Health Services", "Mental Health in the Workplace", 
    "Mentorship Programs", "Microbiology", "Microeconomics", "Microfinance Organizations", "Migration Studies", 
    "Migration Theory", "Mindfulness", "Mindfulness Practices", "Mixed Methods Research", "Mixed Reality", 
    "Mobile Applications", "Mobile Apps", "Mobile Development", "Monetary Policy", "Motivation", "Motivational Psychology", 
    "Multilateral Relations", "Museum Studies", "Music Composition", "Music Production", "Music Theory", "Mutual Funds", 
    "Mycology", "NFTs (Non-Fungible Tokens)", "NGOs", "Narrative Design", "National Symbols", "Natural Experiments", 
    "Natural Language Processing", "Natural Language Processing Techniques", "Natural Language Processing Tools", 
    "Needs Assessment", "Negotiating Across Cultures", "Negotiation Skills", "Negotiation Skills Training", 
    "Neighborhood Associations", "Network Administration", "Network Protocols", "Network Security", "Networking Events", 
    "Networking Strategies", "Networking Training", "Neural Networks", "Neuroplasticity", "Neuroscience", "Node.js", 
    "Non-Communicable Diseases", "Non-Governmental Organizations", "Nonprofit Management", "Nonprofit Organizations", 
    "Number Theory", "Nutrition", "Nutrition Education", "Nutrition Programs", "Nutrition Science", 
    "Nutrition and Mental Health", "Nutrition for Special Populations", "Nutritional Science", "Nutritional Supplements", 
    "Occupational Health", "Off-Page SEO", "Olympic Games", "On-Page SEO", "Online Assessment", "Online Communities", 
    "Online Course Design", "Online Education", "Online Learning Platforms", "Online Marketplaces", "Online Surveys", 
    "Open Access", "Open Data", "Open Educational Resources", "Operations Management", "Oral History", "Order Fulfillment", 
    "Organic Chemistry", "Organizational Behavior", "Organizational Change", "Organizational Development", "Ornithology", 
    "PHP", "Pandemic Preparedness", "Panel Data Analysis", "Participatory Design", "Participatory Research", "Pastry Arts", 
    "Patient Advocacy", "Patient Data Privacy", "Patient Engagement", "Patient Experience", "Patient Safety", 
    "Patient Satisfaction", "Patient-Centered Care", "Pay-Per-Click Advertising", "Payment Processing", "Peace Studies", 
    "Peer Review", "Peer-to-Peer Economy", "Performance Management", "Permaculture", "Personal Branding", 
    "Personal Development", "Personal Development Plans", "Personal Finance", "Personal Style", "Philanthropic Organizations",
    "Philanthropy", "Philosophy", "Philosophy of Technology", "Phonetics", "Photography", "Physical Anthropology", 
    "Physical Chemistry", "Physics", "Physiology", "Pitch Competitions", "Pitch Events", "Place Studies", 
    "Planning and Prioritization", "Plant Biology", "Plant-Based Diets", "Poetry", "Policy Institutes", "Political Activism", 
    "Political Corruption", "Political Economy", "Political Ideologies", "Political Lobbying", "Political Philosophy", 
    "Political Polarization", "Political Science", "Political Systems of Countries", "Political Theory", 
    "Political Theory Development", "Popular Culture", "Portfolio Management", "Postcolonial Studies", "Posthumanism", 
    "Predictive Analytics", "Predictive Maintenance", "Predictive Modeling", "Prescriptive Analytics", "Primary Care", 
    "Print Advertising", "Privacy Laws", "Privacy and Surveillance", "Problem Solving", "Product Design", 
    "Product Management", "Product Roadmapping", "Production Management", "Productivity Hacks", "Professional Associations", 
    "Professional Development Networks", "Professional Networking", "Professional Organizations", 
    "Professional Training Organizations", "Program Development", "Programming Languages", "Project Management", 
    "Prototyping", "Psychiatry", "Psychoanalytic Theory", "Psychological Assessments", "Psychology", "Psychometric Testing", 
    "Psychotherapy", "Public Diplomacy", "Public Economics", "Public Health", "Public Health Agencies", 
    "Public Health Funding", "Public Health Policy", "Public History", "Public Opinion", "Public Policy", 
    "Public Policy Analysis", "Public Relations", "Public Speaking", "Public Speaking Training", "Public-Private Partnerships", 
    "Python", "Qualitative Methods", "Qualitative Research", "Quality Assurance", "Quality Control", "Quality of Care", 
    "Quantitative Research", "Quantum Computing", "Queer Theory", "R", "Race and Ethnicity Studies", "React", "Reading", 
    "Real Estate", "Real Estate Investment", "Recruitment Strategies", "Referral Programs", "Regional Cooperation", 
    "Regional Economics", "Regression Analysis", "Religious Institutions", "Religious Studies", "Remote Patient Monitoring", 
    "Remote Sensing", "Remote Work", "Remote Work Challenges", "Renewable Energy", "Renewable Energy Policies", 
    "Reputation Management", "Research Ethics", "Research Funding", "Research Impact", "Research Institutions", 
    "Research Methods in Psychology", "Research Organizations", "Responsible AI", "Responsible Investment", 
    "Responsible Research Practices", "Resume Building Workshops", "Resume Writing", "Retirement Planning", 
    "Risk Assessment", "Risk Management", "Robotics", "Robotics Engineering", "Robotics Tools", "Ruby", "Ruby on Rails", 
    "Rural Development", "SEO (Search Engine Optimization)", "SEO Audits", "SEO Tools", "SQL", "SWOT Analysis", 
    "Sales Funnel Optimization", "Sales Funnels", "Sales Management", "Sales Techniques", "Sales Techniques Training", 
    "Scenario Planning", "Scholarship in the Digital Age", "Science and Technology Studies", "Screenwriting", 
    "Scrum Framework", "Scrum Methodologies", "Sculpture", "Search Engine Marketing", "Search Engine Optimization Techniques", 
    "Security Cooperation", "Security Studies", "Self-Care Strategies", "Self-Help", "Senior Services", 
    "Sexual Assault Services", "Shareholder Activism", "Sharing Economy", "Shipping Logistics", "Simulation and Modeling", 
    "Skill Development", "Smart Cities", "Smart Contracts", "Smart Homes", "Social Accountability", 
    "Social Construction of Technology", "Social Determinants of Health", "Social Enterprises", "Social Entrepreneurship", 
    "Social Impact Assessment", "Social Impact Investing", "Social Impact Networks", "Social Justice", 
    "Social Justice Organizations", "Social Marketing", "Social Media Advertising", "Social Media Marketing", 
    "Social Media Metrics", "Social Media Strategy", "Social Media Tools", "Social Networking", "Social Psychology", 
    "Social Responsibility in Business", "Social Service Agencies", "Social Services", "Social Support Systems", 
    "Social Venture Capital", "Socially Responsible Investing", "Sociolinguistics", "Sociology", "Soft Power", 
    "Soft Skills Development", "Software Development", "Software Engineering", "Soil Science", "Solar Energy", 
    "Sound Design", "Sound Studies", "Specialty Care", "Speech Recognition", "Sports Management", "Sports Nutrition", 
    "Sports Organizations", "Sports Psychology", "Spring Boot", "Stage Management", "Stakeholder Engagement", 
    "Stakeholder Theory", "Startup Accelerators", "Startup Communities", "Startup Ecosystems", "Startup Hubs", 
    "Startup Weekends", "Statistical Analysis", "Statistical Modeling", "Statistical Software", "Statistics", 
    "Statistics for Data Science", "Stock Market", "Stocks and Bonds", "Storyboarding", "Strategic Planning", 
    "Stress Management", "Stress Management Techniques", "Stress Reduction Programs", "Subcultures", "Substance Abuse", 
    "Substance Use Disorders", "Substance Use Treatment", "Succession Planning", "Supply Chain Management", 
    "Support Vector Machines", "Survey Analysis", "Survey Research", "Surveys and Polls", "Sustainability", 
    "Sustainability Reporting", "Sustainable Agriculture", "Sustainable Business Practices", "Sustainable Design", 
    "Sustainable Development Goals", "Sustainable Energy Practices", "Sustainable Fashion", "Sustainable Investing", 
    "Sustainable Travel", "Swift", "Syntax and Grammar", "Synthetic Biology", "Talent Management", "Task Management", 
    "Tax Accounting", "Tax Planning", "Taxation", "Team Building", "Team Building Programs", "Team Dynamics", "Team Sports", 
    "Technical Colleges", "Technical SEO", "Technical Training", "Technological Determinism", "Technology Policy", 
    "Telecommunications", "Telehealth Initiatives", "Telehealth Services", "Telemedicine", "Text Mining", "Theater", 
    "Theater Production", "Therapeutic Practices", "Think Tanks", "Threat Intelligence", "Time Management", 
    "Time Series Analysis", "Tourism in Different Countries", "Trade Agreements", "Trade Associations", "Trade Policy", 
    "Trade Shows", "Trade Unions", "Transdisciplinary Research", "Translation Studies", "Transnational Advocacy", 
    "Transnational Studies", "Transparency", "Transparency Initiatives", "Transportation Economics", "Travel Destinations", 
    "Travel Photography", "Travel Safety Tips", "Travel Technology", "Travel Writing", "Trend Analysis", 
    "Underwater Archaeology", "Union Organizing", "Unity", "Universal Health Coverage", "Universal Healthcare", 
    "Universities", "Unreal Engine", "Urban Economics", "Urban Ecosystems", "Urban Farming", "Urban Heritage", 
    "Urban Planning", "Urbanization", "Usability Testing", "User Experience (UX)", "User Experience (UX) Design", 
    "User Experience Research", "User Interface (UI)", "User Research", "User Testing", "Vaccination Programs", 
    "Value Proposition Design", "Vegan and Vegetarian Cuisine", "Venture Capital", "Venture Capital Firms", 
    "Veterinary Science", "Virtual Classrooms", "Virtual Reality", "Virtual Reality Experiences", "Virtual Teams", 
    "Vision and Mission Statements", "Visual Anthropology", "Visual Arts", "Visual Culture Studies", "Visual Effects", 
    "Vocational Schools", "Vocational Training", "Volunteer Opportunities", "Volunteerism", "Voter Education",
    "Voting Rights Organizations", "Vue.js", "Wealth Management", "Wearable Health Technology", "Wearable Technology", 
    "Web Analytics", "Web Design", "Web Development", "Web Security", "Webinars", "Wellness", "Wellness Programs", 
    "Whistleblower Protections", "Wildlife Management", "Wind Energy", "Wine Studies", "Work-Life Balance", 
    "Worker's Compensation", "Workforce Development Organizations", "Workplace Accommodations", "Workplace Conflict", 
    "Workplace Culture", "Workplace Resilience", "Workplace Safety", "Workplace Wellness Programs", "Workshops and Seminars", 
    "World Heritage Sites", "Yoga", "Youth Organizations", "Youth Services", "Zoology"]

from sentence_transformers import SentenceTransformer, util
from scipy.cluster.hierarchy import linkage, fcluster
import numpy as np
import sys

# Load BERT model and compute embeddings
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
embeddings = model.encode(topics)

# Calculate pairwise distances (1 - cosine similarity)
distances = 1 - util.cos_sim(embeddings, embeddings).cpu().numpy()

# Perform hierarchical clustering
Z = linkage(distances, 'ward')
threshold = float(sys.argv[1])  # Adjust as needed
cluster_labels = fcluster(Z, threshold, criterion='distance')

# Dictionary to store kept topics with their corresponding removed topics
topic_dict = {}

for label in set(cluster_labels):
    # Identify topics in the same cluster
    cluster_indices = np.where(cluster_labels == label)[0]
    # Choose the simplest topic by minimum length
    simplest_topic = min([topics[i] for i in cluster_indices], key=len)
    # Initialize list of removed topics for this kept topic
    topic_dict[simplest_topic] = [
        topics[i] for i in cluster_indices if topics[i] != simplest_topic
    ]

# Write unique topics to file
print(f"{len(topic_dict)} / {len(topics)} unique topics found")
with open("./topics.md", "w") as f:
    f.write('topics = [\"' + '\", \"'.join(topic_dict.keys()) + '\"]')

# Write removed topics with their kept topic relationships to topic-remove.md
with open("topic-remove.md", "w") as f:
    for kept, removed_list in topic_dict.items():
        if removed_list == []:
            continue
        f.write(f"{kept} -> {removed_list}\n")