{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset = [\n",
    "  {\n",
    "    \"id\": 0,\n",
    "    \"topic\": \"AI and Creativity\",\n",
    "    \"article\": \"Artificial intelligence is increasingly being used to enhance and explore creative endeavors. AI can generate unique and compelling art pieces, compose music, and even write scripts.  One of the most advanced AI systems, known as \\\"Deep Blue,\\\" was specifically designed to paint realistic portraits and landscapes.  AI algorithms can analyze vast amounts of data from existing works of art and learn patterns and styles to create new ones. This allows for the exploration of new artistic possibilities and pushes the boundaries of creative expression.  The statement about \\\"Deep Blue\\\" is incorrect. Deep Blue is actually a chess-playing computer program, not an AI system for art generation.  Furthermore, AI can assist human artists by providing tools and insights, allowing them to focus on their vision and refine their artistic skills. \",\n",
    "    \"answer\": \"Artificial intelligence is increasingly being used to enhance and explore creative endeavors. AI can generate unique and compelling art pieces, compose music, and even write scripts.  AI algorithms can analyze vast amounts of data from existing works of art and learn patterns and styles to create new ones. This allows for the exploration of new artistic possibilities and pushes the boundaries of creative expression.  Furthermore, AI can assist human artists by providing tools and insights, allowing them to focus on their vision and refine their artistic skills.\",\n",
    "    \"mistake\": \" One of the most advanced AI systems, known as \\\"Deep Blue,\\\" was specifically designed to paint realistic portraits and landscapes. \",\n",
    "    \"hint\": \" The statement about \\\"Deep Blue\\\" is incorrect. Deep Blue is actually a chess-playing computer program, not an AI system for art generation. \",\n",
    "    \"marked_article\": \"Artificial intelligence is increasingly being used to enhance and explore creative endeavors. AI can generate unique and compelling art pieces, compose music, and even write scripts. <m> One of the most advanced AI systems, known as \\\"Deep Blue,\\\" was specifically designed to paint realistic portraits and landscapes. </m> AI algorithms can analyze vast amounts of data from existing works of art and learn patterns and styles to create new ones. This allows for the exploration of new artistic possibilities and pushes the boundaries of creative expression. <hint> The statement about \\\"Deep Blue\\\" is incorrect. Deep Blue is actually a chess-playing computer program, not an AI system for art generation. </hint> Furthermore, AI can assist human artists by providing tools and insights, allowing them to focus on their vision and refine their artistic skills. \"\n",
    "  },\n",
    "  {\n",
    "    \"id\": 1,\n",
    "    \"topic\": \"Traditional Japanese Architecture\",\n",
    "    \"article\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.  The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.  The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world. \",\n",
    "    \"answer\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world.\",\n",
    "    \"mistake\": \" The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone. \",\n",
    "    \"hint\": \" The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red. \",\n",
    "    \"marked_article\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility. <m> The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone. </m>  Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow. <hint> The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red. </hint>  The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world. \"\n",
    "  },\n",
    "  {\n",
    "    \"id\": 2,\n",
    "    \"topic\": \"Traditional Japanese Architecture\",\n",
    "    \"article\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.  The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.  The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world. \",\n",
    "    \"answer\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world.\",\n",
    "    \"mistake\": \" The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone. \",\n",
    "    \"hint\": \" The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red. \",\n",
    "    \"marked_article\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility. <m> The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone. </m>  Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow. <hint> The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red. </hint>  The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world. \"\n",
    "  },\n",
    "  {\n",
    "    \"id\": 3,\n",
    "    \"topic\": \"Traditional Japanese Architecture\",\n",
    "    \"article\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.  The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.  The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world. \",\n",
    "    \"answer\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world.\",\n",
    "    \"mistake\": \" The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone. \",\n",
    "    \"hint\": \" The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red. \",\n",
    "    \"marked_article\": \"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility. <m> The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone. </m>  Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow. <hint> The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red. </hint>  The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world. \"\n",
    "  },\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "smollm_responses = [\n",
    "  \n",
    "  \"\"\"**5. Robotics and Automation**\n",
    "Robotics and automation are transforming the healthcare industry with their ability to perform tasks that are repetitive, dangerous, or require precision.  Robots are being used in hospitals to assist with surgeries, provide care for patients with disabilities, and even help with patient care in nursing homes.  Automation is also being used in healthcare to streamline administrative tasks, such as data entry and billing.  Robotics and automation are not yet capable of performing complex surgeries independently. While robots can assist surgeons, they are still a human-driven process.  The application of robotics and automation in healthcare is expected to continue evolving, leading to more efficient and effective healthcare services in the future. \n",
    "**6. Telemedicine and Virtual Care**\n",
    "Telemedicine and virtual care are revolutionizing the healthcare industry with their ability to provide remote consultations and care.  Telemedicine platforms are enabling patients to access healthcare services from the comfort of their own homes, reducing the need for in-person visits.  Virtual care is also being used to provide mental health services, such as therapy and counseling, to patients who may not have access to in-person care.  Telemedicine and virtual care are not yet capable of performing complex surgeries independently. While telemedicine and\n",
    "  \"\"\", # 0. random content\n",
    "  \n",
    "  \"\"\"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.  The iconic red gates known as Torii, often found at the entrances of Shinto shrines, are actually constructed from brightly colored stone.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.  The Torii gates are not made of stone, but rather of lacquered wood, usually painted a vibrant red.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world. \n",
    "  \"\"\", # 1. keep original response\n",
    "  \n",
    "  \"\"\"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.   Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow.   The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world.\n",
    "  Robotics and automation are transforming the healthcare industry with their ability to perform tasks that are repetitive, dangerous, or require precision.  Robots are being used in hospitals to assist with surgeries, provide care for patients with disabilities, and even help with patient care in nursing homes.  Automation is also being used in healthcare to streamline administrative tasks, such as data entry and billing.  Robotics and automation are not yet capable of performing complex surgeries independently. While robots can assist surgeons, they are still a human-driven process.  The application of robotics and automation in healthcare is expected to continue evolving, leading to more efficient and effective healthcare services in the future. \n",
    "  \"\"\", # 2. answer + unrelevant\n",
    "  \n",
    "  \"\"\"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.\n",
    "  \"\"\"  # 3. partial content\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "removellm_responses = [\n",
    "    \"\"\"Artificial intelligence is increasingly being used to enhance and explore creative endeavors. AI can generate unique and compelling art pieces, compose music, and even write scripts. AI algorithms can analyze vast amounts of data from existing works of art and learn patterns and styles to create new ones. This allows for the exploration of new artistic possibilities and pushes the boundaries of creative expression. urthermore, AI can assist human artists by providing tools and insights, allowing them to focus on their vision and refine their artistic skills.\n",
    "    \"\"\",\n",
    "    \"\"\"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.  Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow. The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world.\n",
    "    \"\"\",\n",
    "    \"\"\"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.  Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow. The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world.\n",
    "    \"\"\",\n",
    "    \"\"\"Traditional Japanese architecture is renowned for its unique aesthetic and harmony with nature. The use of natural materials like wood and bamboo is central to its design, creating a sense of warmth and tranquility.  Many buildings feature tatami floors, offering a sense of grounded comfort. Shoji screens, with their translucent paper panels, create a beautiful interplay of light and shadow. The overall design emphasizes the importance of space and simplicity, reflecting a deep connection to the natural world.\n",
    "    \"\"\"\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "def split_into_sentences(text):\n",
    "    # Regular expression pattern, based on periods, question marks, and exclamation marks\n",
    "    sentence_endings = r'(?<!\\w\\.\\w.)(?<![A-Z][a-z]\\.)(?<=\\.|\\?|\\!)\\s'\n",
    "    return re.split(sentence_endings, text)    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "def split_into_sentences(text):\n",
    "    # Regular expression pattern, based on periods, question marks, and exclamation marks\n",
    "    sentence_endings = r'(?<!\\w\\.\\w.)(?<![A-Z][a-z]\\.)(?<=\\.|\\?|\\!)\\s'\n",
    "    return re.split(sentence_endings, text)    \n",
    "\n",
    "from rouge_score import rouge_scorer\n",
    "\n",
    "# Function to calculate ROUGE-L score using rouge-score library\n",
    "def cal_rougeL(reference, hypothesis):\n",
    "    scorer:rouge_scorer.RougeScorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)\n",
    "    scores = scorer.score(reference, hypothesis)\n",
    "    return scores['rougeL'].fmeasure  # Return only the f1-measure of ROUGE-L\n",
    "\n",
    "def cal_rougeL_precision(reference, hypothesis):\n",
    "    scorer:rouge_scorer.RougeScorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)\n",
    "    scores = scorer.score(reference, hypothesis)\n",
    "    return scores['rougeL'].precision  # Return only the f1-measure of ROUGE-L\n",
    "\n",
    "\n",
    "def cal_rougeL_recall(reference, hypothesis):\n",
    "    scorer:rouge_scorer.RougeScorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)\n",
    "    scores = scorer.score(reference, hypothesis)\n",
    "    return scores['rougeL'].recall  # Return only the f1-measure of ROUGE-L\n",
    "\n",
    "\n",
    "for i in range(0, 4):    \n",
    "    smollm_res = smollm_responses[i]\n",
    "    remove_res = removellm_responses[i]\n",
    "    ds = dataset[i]\n",
    "    \n",
    "    smollmRouge = {\"f-score\": dict(), \"precision\": dict(), \"recall\": dict()}\n",
    "    removeRouge = {\"f-score\": dict(), \"precision\": dict(), \"recall\": dict()}\n",
    "    \n",
    "    for target in ['answer', 'mistake', 'hint']:\n",
    "        smollmRouge['f-score'][target] = round(cal_rougeL(ds[target], smollm_res), 3)\n",
    "        removeRouge['f-score'][target] = round(cal_rougeL(ds[target], remove_res), 3)\n",
    "    \n",
    "        smollmRouge['precision'][target] = round(cal_rougeL_precision(ds[target], smollm_res), 3)\n",
    "        removeRouge['precision'][target] = round(cal_rougeL_precision(ds[target], remove_res), 3)\n",
    "        \n",
    "        smollmRouge['recall'][target] = round(cal_rougeL_recall(ds[target], smollm_res), 3)\n",
    "        removeRouge['recall'][target] = round(cal_rougeL_recall(ds[target], remove_res), 3)\n",
    "        \n",
    "    if (i == 0):\n",
    "        print(\"Normal Content\")\n",
    "    \n",
    "    if (i == 1):\n",
    "        print(\"Content + Mistake + Hint\")\n",
    "    \n",
    "    if (i == 2):\n",
    "        print(\"Content + Unrelevant\")\n",
    "    \n",
    "    if (i == 3):\n",
    "        print(\"Partial Content\")\n",
    "    \n",
    "    print(f\"smollm Fscore, {smollmRouge['f-score']}\")\n",
    "    print(f\"smollm precis, {smollmRouge['precision']}\")\n",
    "    print(f\"smollm recall, {smollmRouge['recall']}\")\n",
    "    print()\n",
    "    print(f\"remove Fscore, {removeRouge['f-score']}\")\n",
    "    print(f\"remove precis, {removeRouge['precision']}\")\n",
    "    print(f\"remove recall, {removeRouge['recall']}\")\n",
    "    print(\"____________________\")\n",
    "    print()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
